### ISSUE TITLE
Sources selection

### ISSUE THREAD

**Issue by gitkuba** [bethinkpl/bit-docs#20]
@bethinkpl/bit 
I'm thinking of a change in document template, that would help distinguish sources suitable for diffrent competence levels.

So I've got 3 ideas:

1. Below classification questions for a given level e.g.:
> ### Apprentice aka _I know what Web is_:
> - I can explain how does the Web work and what are its most fundamental building blocks.
> - I can tell the difference between the Web and the Internet.
> - I know what a web browser is.
> - I know what a web server is.
> 
> **Where to look for answers**:
> - https://en.wikipedia.org/wiki/World_Wide_Web
> - https://www.youtube.com/watch?v=J8hzJxb0rpc

2. In sources section, wrapped up in parentheses:

> ## Sources
> 
> ### Books
> - [Laravel: Up & Running: A Framework for Building Modern PHP Apps](https://laravelupandrunning.com/) (beginner - advanced)
> 
> ### Video
> - [Laravel 5.7 From Scratch](https://laracasts.com/series/laravel-from-scratch-2018) (beginner)
> 
> ### Read online
> - [Laravel Tutorial: Step by Step Guide to Building Your First Laravel Application](https://laravel-news.com/your-first-laravel-application) (intermediate)
> - [Laravel official docs](https://laravel.com/docs/) (beginner - advanced)

3. sources organized in a table?: 

| Level | Books | Video | Read online | 
| --- | --- | --- | --- |
| Apprentice | [Laravel: Up & Running: A Framework for Building Modern PHP Apps](https://laravelupandrunning.com/) | [Laravel 5.7 From Scratch](https://laracasts.com/series/laravel-from-scratch-2018) | - |
| Intermediate  | [Laravel: Up & Running: A Framework for Building Modern PHP Apps](https://laravelupandrunning.com/) | - | [Laravel Tutorial: Step by Step Guide to Building Your First Laravel Application](https://laravel-news.com/your-first-laravel-application) |
| Advanced  | [Laravel: Up & Running: A Framework for Building Modern PHP Apps](https://laravelupandrunning.com/) | - | - |
| Master  | - | - | - |

Sooo... how about it?

**Comment by kvas-damian** [comment]
Great idea. It'll definitely help to pick the right source at the right time. I'd suggest being consistent with the level naming.

Personally, I like 2nd and 1st option more than the last one. A lot of duplicated links in the table are hard to maintain, also multiple positions at one level will make the table more complex and probably less readable.

I can't decide what's more important: to see a list of sources at the current level vs list of all publications in one place where I can choose from?

**Comment by rogatty** [comment]
I think the first option is better in terms of getting what you need, when you need it. It's problematic, though, when you're not sure which level it suits or when it suits all levels (duplication). I'm fine with the 1st and the 2nd, the 3rd is too bloated.

**Comment by kvas-damian** [comment]
@gitkuba any plan on moving forward with this issue?

**Comment by kvas-damian** [comment]
We agreed to use scenario 2. Followup in #25
